name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-3.12-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-3.12-
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests with pytest
      run: |
        python -m pytest test_calculator.py -v --tb=short
    
    - name: Run basic syntax check
      run: |
        python -m py_compile calculator.py
        python -m py_compile main.py
        python -m py_compile test_calculator.py
    
    - name: Check code formatting with black
      run: |
        python -c "import black; print('Black is available')" 2>/dev/null || echo "Black not installed, skipping formatting check"
        python -m black --check . 2>/dev/null || echo "Black check failed or not installed"
      continue-on-error: true

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    
    - name: Cache pip dependencies for linting
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-lint-3.12-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-lint-3.12-
          ${{ runner.os }}-pip-lint-
          ${{ runner.os }}-pip-
    
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint
    
    - name: Run flake8 (style and basic errors)
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      continue-on-error: true
    
    - name: Run pylint (complex analysis)
      run: |
        pylint calculator.py main.py test_calculator.py --disable=C0114,C0116
        exit_code=$?
        echo "Pylint exit code: $exit_code"
        
        # Allow these exit codes (non-blocking):
        # 0: No issues
        # 8: Refactor message (code style suggestions)
        # 16: Convention message (naming conventions)
        # 24: Refactor + Convention (8 + 16)
        if [[ $exit_code -eq 0 || $exit_code -eq 8 || $exit_code -eq 16 || $exit_code -eq 24 ]]; then
          echo "Pylint passed or only found style/convention issues (exit code: $exit_code)"
          exit 0
        else
          echo "Pylint found serious issues (exit code: $exit_code)"
          exit $exit_code
        fi 